-- 코드를 입력하세요
WITH RECURSIVE cte_count
AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1
    FROM cte_count 
    WHERE n < 23
)

SELECT n 'HOUR', 0
FROM cte_count
WHERE  n NOT IN (SELECT HOUR(DATETIME) HOUR
    FROM ANIMAL_OUTS
    GROUP BY HOUR)
UNION ALL
SELECT HOUR(DATETIME) as HOUR, COUNT(ANIMAL_ID) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
ORDER BY HOUR