SELECT F2.FLAVOR
FROM FIRST_HALF F2
JOIN (SELECT F1.FLAVOR, SUM(J.TOTAL_ORDER) AS JULY_SUM
      FROM FIRST_HALF F1
      JOIN JULY J
      ON F1.FLAVOR = J.FLAVOR
      GROUP BY F1.FLAVOR ) JS
ON F2.FLAVOR = JS.FLAVOR
ORDER BY F2.TOTAL_ORDER + JS.JULY_SUM DESC
LIMIT 3