-- 코드를 입력하세요
# SELECT i.ANIMAL_ID, i.NAME
# FROM ANIMAL_OUTS o
# JOIN ANIMAL_INS i
# ON o.ANIMAL_ID = i.ANIMAL_ID
# WHERE o.DATETIME < i.DATETIME
# ORDER BY i.DATETIME

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME < I.DATETIME
ORDER BY I.DATETIME